### ISSUE TITLE
Crash on player join

### ISSUE THREAD

**Issue by Billy-S** [joe7575/techpack#14]
Hello again,
It seems tubelib has some sort of bug ... this is the error:
`2019-04-06 01:23:39: ERROR[Main]: ServerError: AsyncErr: ServerThread::run Lua: Runtime error from mod '' in callback node_on_timer(): ...llys/.minetest/mods/techpack/tubelib/node_states.lua:308: bad argument #1 to 'random' (interval is empty)
2019-04-06 01:23:39: ERROR[Main]: stack traceback:
2019-04-06 01:23:39: ERROR[Main]: 	[C]: in function 'random'
2019-04-06 01:23:39: ERROR[Main]: 	...llys/.minetest/mods/techpack/tubelib/node_states.lua:308: in function 'keep_running'
2019-04-06 01:23:39: ERROR[Main]: 	...minetest/mods/techpack/tubelib_addons1/harvester.lua:258: in function <...minetest/mods/techpack/tubelib_addons1/harvester.lua:245>`

The crash happened whenever a certain player joins.  To me, the issue seems to be that if `self.aging_level2/num_items` is `0` or `inf` (from a divide by zero issue), then math.random errors.

Thanks,
BillyS

PS.
For now I've hacked together a solution to prevent it from crashing, but it's probably not the best way.  So, this isn't terribly urgent but it should still be fixed.  Thanks :)

**Comment by joe7575** [comment]
Hi Billy,
I can't reproduce this bug.
The error message `bad argument #1 to 'random' (interval is empty)` is strange.
A search points to problems with huge numbers as arguments. In this case (`math.random(self.aging_level2/num_items)`) num_items is probably 1 and self.aging_level2 should be 6000. So I assume the data behind 'self' is corrupt due to an earlier crash.
I will change the code so that the data will be checked when the node is loaded.  But something like
`math.min(self.aging_level2, 10000)` should work

**Comment by Billy-S** [comment]
Hmmm, alright.  However, I don't know how `num_items` is stored, but if it was zero it could cause that error.  Also, I know that `meta:get_int(key)` returns `0` when there is no entry under `key`.  So if `num_items` is stored in node metadata, something like that might have happened.

**Comment by joe7575** [comment]
If num_items is zero, it results in a `inf` error. If one value is nil, I get a `attempt to perform arithmetic on a nil value` or a `bad argument #1 to 'random' (number expected, got nil)`, but never the `bad argument #1 to 'random' (interval is empty)`. So, I do not really understand...

**Comment by Billy-S** [comment]
Hmm, that's very odd then.  Maybe we are using different versions of lua.  Well, thanks for your help ... :)
