### ISSUE TITLE
compatability: node replacement tool

### ISSUE THREAD

**Issue by obl3pplifp** [joe7575/techpack#17]
(feature request)

The node replacement tool from https://github.com/Sokomine/replacer does not work well with techpack blocks (mostly tubelib). For instance, tubelib machines that are placed with this tool do not get any WLAN (machine?) ID. I don't know what a solution to this problem looks like; it may have to be fixed on the replacement tool's side.

**Comment by joe7575** [comment]
I checked the code, the replacement tool has a black list:
`replacer.blacklist = {};`
All nodes could be added to this list.

**Comment by joe7575** [comment]
I implemented a different approach, which will detect any modification from all move/copy/replace tools.
Each node stored its position as meta data and checks this cyclically. If the node is moved/copied/replaced, it will switch to the state "defect" (dummy node).
This modification has to be added to all machine timer functions like:
`local function keep_running(pos, elapsed)
	if tubelib.data_not_corrupted(pos) then
		local meta = M(pos)
		distributing(pos, meta)
		return State:is_active(meta)
	end
	return false
end
`
The function `data_not_corrupted(pos)` is implemented in the file defect.lua.
When it is called the first time, it will do some addition checks.
For each further call, it will only check the position.

It should be possible to adapt this also to your version. But you should test it on a test installation, otherwise all your machines can become useless
